name = "Nestings"
uuid = "4c0ff9d7-9bb8-48f3-9b8d-cd606a2df668"
authors = ["ch"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
